[project]
name = "virtual-land"
authors = ["Your Name"]
description = "A smart contract for virtual land ownership and trading"
telemetry = false
requirements = []

[contracts.virtual-land]
path = "contracts/virtual-land.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
